import Link from 'next/link'

export default function About() {
  return (
    <main className="container">
      <h1>About</h1>
      <p>This site was generated by an automated assistant as a starter Next.js app.</p>
      <p>
        <Link href="/">Home</Link>
      </p>
    </main>
  )
}
